routes/web.php
<?php

use App\Http\Controllers\crud;
use App\Http\Controllers\game;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfilController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('/sesi/awal') ;
});

Route::get('/sesi',[SessionController::class, 'index']);
Route::post('/sesi/login',[SessionController::class, 'login']);
Route::get('/register',[SessionController::class, 'register']);
Route::post('/sesi/register',[SessionController::class, 'createakun']);
Route::get('/sesi/logout',[SessionController::class, 'logout']);


Route::get('/admin',[SessionController::class, 'admin']);
// route user
Route::get('/user',[SessionController::class, 'user']);
Route::get('/kategori',[UserController::class, 'kategori']);

// crud
// create
Route::post('/create/admin',[crud::class, 'createadmin']);
Route::post('/create/game/action',[crud::class, 'creategame']);
Route::post('/detail',[crud::class, 'panggilgame']);
Route::post('/favorit',[game::class, 'favorit']);
Route::post('/komentar',[game::class, 'komentar']);




// read
Route::get('/create/user',[crud::class, 'userform']);
Route::get('/create/game',[crud::class, 'gameform']);
Route::post('/kategori/more',[game::class, 'morekategori']);
Route::post('/view',[game::class, 'viewgame']);






// Route::get('/detail',[game::class, 'tampil']);
Route::get('/userlist',[crud::class, 'user']);
Route::get('/export',[crud::class, 'export']);
Route::get('/gamelist',[crud::class, 'game']);
Route::post('/gamelist/kategori',[crud::class, 'gamekategori']);



// update
Route::post('/ingame',[crud::class, 'updategame']);
Route::post('/game/update',[crud::class, 'aksiupdate']);




// delete
Route::post('userlist/delete',[crud::class, 'userdlt']);
Route::post('gamelist/delete',[crud::class, 'gamedlt']);

// cari
Route::get('/game/cari',[SessionController::class, 'cari']);


// profil
Route::resource('/profil', ProfilController::class);

// cart
Route::get('/cart',[game::class, 'cart']);
Route::post('/addcart',[game::class, 'addcart']);
Route::post('cart/delete',[game::class, 'cartdlt']);


// komentar
Route::get('/komentar',[UserController::class, 'komentars']);
Route::post('komentar/delete',[UserController::class, 'komendlt']);


// discount
Route::get('/discount',[UserController::class, 'discount']);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // sambungan one to many ke table users
    public function role() {
        return $this->belongsTo(Role::class, 'role_id');
    }
    public function komentar() {
        return $this->belongsTo(Role::class, 'user_id');
    }
    public function profil() {
        return $this->belongsTo(profil::class, 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\cart;
use App\Models\games;
use App\Models\kategori;
use App\Models\komentar;
use App\Models\profil;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    function kategori(){
        $action = DB::table('kategoris')->where('kategori_id', [4])->first();
        $simulator = DB::table('kategoris')->where('kategori_id', [2])->first();
        $fps = DB::table('kategoris')->where('kategori_id', [1])->first();
        $rpg = DB::table('kategoris')->where('kategori_id', [3])->first();

        $kukang = kategori::latest()->paginate(4);
        $dataku = kategori::all();
        $data = DB::table('games')->where('kategori_id', [2])->paginate(6);
        return view('sesi/user/kategori')->with('data', $data)->with('dataku',$dataku)->with('kakangku',$kukang)->with('action' , $action)->with('simulator', $simulator)->with('fps', $fps)->with('rpg', $rpg);
    }

    function komentars(){
        $id = auth()->user()->id;
        $komentar = komentar::all()->where('user_id', $id);
        $user = profil::all()->where('user_id', $id);
        return view('/sesi/user/komentar')->with('komen',$komentar)->with('user', $user);
    }

    function komendlt(Request $request){
        $request->validate([
            'id' => 'required']);
        komentar::where('id', $request->id)->delete();
        return redirect('/komentar');


    }

    function discount(){
        $game = games::all()->where('status_game', 'diskon');
        return view('/sesi/user/discount')->with('games', $game);
    }



}

resources/views/sesi/user/cart.blade.php
@extends('basic.main')
@include('komponen.usernavbar')
@include('komponen.navushome')

@section('konten')
<h1>saya suka keqingggg</h1>
<div class="w-100 d-flex justify-content-center">
    <div class="layer row row-col-2 ">
        @foreach($game as $item)
        @php $games = DB::table('games')->where('game_id', $item->game_id)->first(); @endphp
        @php $path = Storage::url('imgs/'.$games->poster_file); @endphp 
        @php
            $diskon = $games->harga_game - $games->harga_diskon;
        @endphp
        <div class="card me-2 bg-dark border border-light" style="width: 18rem;">
            <img src="{{ url($path) }}"alt="" height="400px" srcset=""class="mt-2 card-img-top" >
            <div class="card-body">
                <h5 class="fw-bold text-light ms-3  mt-1" >{{ $games->name_game }}</h5>
                <h5 class="fw-bold text-light ms-3  mt-1" >Rp.{{ $diskon }}</h5>
                <form class="  " action="/detail" method="POST">
                    @csrf
                    <input type="hidden" name="game_id" value="{{ $games->game_id }}">
                    <input type="hidden" name="kategori_id" value="{{ $games->kategori_id }}">
                    <button type="submit" name="submit" class="w-100 btn btn-outline-primary">Detail</button>
                </form>
                <form class=" " action="cart/delete" method="POST">
                    @csrf
                    <input type="hidden" name="id" value="{{ $item->id }}">
                    <button type="submit" name="submit" class="w-100 btn btn-outline-danger">Delete</button>
                </form>
            </div>
          </div>


    @endforeach
    </div>

</div>

@endsection

resources/views/sesi/user/discount.blade.php
@extends('basic.main')
@include('komponen.usernavbar')
@include('komponen.navushome')

@section('konten')

<div class="w-100 d-flex justify-content-center">
    <div class="w-75 d-flex justify-content-start">
    @foreach($games as $item)
    @php $path = Storage::url('imgs/'.$item->poster_file); @endphp
    @php $games = DB::table('games')->where('game_id', $item->game_id)->first(); @endphp 
    @php
        $diskon = $games->harga_game - $games->harga_diskon;
    @endphp

    <div class="game rounded col-md-3 bg-dark m-2 mb-5 mt-5" style="width: 16rem;">
        <img src="{{ url($path) }}"alt="" srcset="" class="rounded-top" width="100%">
        <div class="ms-2">
            <h5 class="fw-bold text-light  mt-1" style="height: 10%">{{ $item->name_game }}</h5>
            <div class="d-flex" style="height: 10%">
            <div>
                <p class="fw-bold text-decoration-line-through fst-italic fw-light text-secondary">Rp.{{$item->harga_game}}</p>
                <p class="fw-bold text-light m-0">Rp.{{ $diskon }}</p>
            </div>
            <form class="w-100 justify-content-end text-center mt-4" action="/detail" method="POST">
                @csrf
                <input type="hidden" name="game_id" value="{{ $item->game_id }} col-md-6">
                <input type="hidden" name="kategori_id" value="{{ $item->kategori_id }} col-md-6">
                <button type="submit" name="submit" class="w-75 btn btn-outline-light">Detail</button>
            </form>
            </div>

        </div>
    </div>
    @endforeach
    </div>
</div>

@endsection

resources/views/sesi/user/game.blade.php
@extends('basic/main')
@include('komponen.usernavbar')
@include('komponen/navushome')

@section('konten')
@php $path = Storage::url('imgs/'.$dataku->video_file); @endphp
@php $path2 = Storage::url('imgs/'.$dataku->banner_file); @endphp
@php $path3 = Storage::url('imgs/'.$dataku->gameplay_file); @endphp


<div class="w-100 d-flex justify-content-center">
    <div class="layer">
        <form action="/favorit" method="post" class="w-100 text-end">
            @csrf
            <input type="hidden" name="game_id" value="{{ $dataku->game_id }}">
            <input type="hidden" name="user_id" value="{{ $user_id->user_id }}">
            <input type="hidden" name="kategori_id" value="{{ $dataku->kategori_id }} col-md-6">
            <button type="submit" name="submit" class="btn btn-outline-light">Favorit</button>
        </form>
    </div>
</div>
    <div class="w-100 d-flex justify-content-center" >

        <div class="gameinfo d-flex justify-content-center">
            <div class="d-flex row w-100 justify-content-center mb-4 mt-4" >
                <div class="col-lg-7 rounded play me-1 p-2" style="background-color: rgb(32, 32, 32)">
                    <video controls autoplay loop class="w-full" src="{{ url($path) }}" alt="" srcset="" width="100%" height="auto"></video>
                    <div class=" mt-2 w-100 d-flex justify-content-center">
                        <img class="" src="{{ url($path3) }}" alt="" srcset="" width="100%" height="auto">
                    </div>
    
    
                </div>
                <div class="col-lg-4 rounded  p-2 ms-1 text-light " style="background-color: rgb(32, 32, 32)">
                    <img class="" src="{{ url($path2) }}" alt="" width="100%" height="auto" srcset="">
                    <h3 class="w-75 mt-3">{{ $dataku->name_game }}</h3>
                    <p class="w-100 text-start">Deskripsi : {{ $dataku->deskripsi_game }}</p>
                    <div class="d-flex mt-5 m-4">
                        @foreach ($kategori as $item)
                            <div class="genre bg-dark m-1 text-center w-auto"><p class="p-1 text-light fw-bold">{{ $item->kategori_name }}</p></div>
                        @endforeach
                    </div>
                    
                </div>
            </div>
        </div>
    
    </div>

        <div class="detail ">



            <div class="card text-light w-100" style="background-color: rgb(32, 32, 32)">
                <img src="img/gowasli.png" class="card-img w-100" alt="...">
                <div class="ms-4 card-img-overlay">
                    <h5 class="card-title">Buy now</h5>
                    <p class="card-text text-decoration-line-through fst-italic">$00.000</p>
                    <p class="card-text fw-bold ">$00.000</p>
                    <div class="pt-4 mt-5 w-100 d-flex justify-content-end pe-4">
                        <form action="/addcart" method="post" class="w-100 text-end">
                            @csrf
                            <input type="hidden" name="game_id" value="{{ $dataku->game_id }}">
                            <input type="hidden" name="user_id" value="{{ $user_id->user_id }}">
                            <input type="hidden" name="kategori_id" value="{{ $dataku->kategori_id }} col-md-6">
                            <button class="btn btn-primary w-15 pe-3 ps-3" name="submit" type="submit">Add to cart</button>
                        </form>
                    </div>
                </div>
              </div>

            <div class="w-100 rounded mt-4 deskripsi text-light">
                <h2 class="m-5 pt-4 ">Description</h2>
                <p class="m-5">
                    {{ $dataku->deskripsi_game }}
                </p>
            </div>

            
            <div class="w-100 rounded mt-4 deskripsi text-light">
                <h2 class="m-5 pt-4 ">System Required</h2>
                <p class="m-5">
                    {{ $dataku->deskripsi_game }}
                </p>
            </div>

            <div class="w-100 mt-4">
                <img class="w-100" src="img/yelan2.png" alt="" srcset="">
            </div>

                    

            <div id="carouselExampleAutoplaying" class="carousel slide w-100 mt-3 mb-5" data-bs-ride="carousel" style="height: 400px">
                <div class="carousel-inner">
                    <div class="carousel-item active" >
                        <div class="w-100 rounded mt-4 h-100 text-light deskripsi2">
                            <div class="w-100 d-flex p-4">
                                <img class="rounded-circle " src="img/sakamoto.jpeg" alt="" srcset="" width="100px" height="auto">
                                <h4 class="h-100 m-4 text-center">nama</h4>
            
                            </div>
                            <div class="text-center p-4 pb-5 m-3 mb-5">
                                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos animi necessitatibus, repudiandae ex itaque voluptates nisi tenetur, qui alias cupiditate adipisci incidunt sunt corrupti, voluptatibus quia illo? Aliquid, adipisci laboriosam?</p>
                            </div>
                        </div>
                      </div>
                    @foreach ($komentar as $komen)
                    <div class="carousel-item " v >
                        <div class="w-100 rounded mt-4 h-100 text-light deskripsi2">
                            <div class="w-100 d-flex p-4">
                                <img class="rounded-circle " src="img/sakamoto.jpeg" alt="" srcset="" width="100px" height="auto">
                                <h4 class="h-100 m-4 text-center">nama</h4>
            
                            </div>
                            <div class="text-center p-4 pb-5 m-3 mb-5">
                                <p>{{ $komen->komentar }}{{ $komen->komentar }}</p>
                            </div>
                        </div>
                      </div>
                      @endforeach
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                </div>
                {{-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button> --}}
              </div>


            <div class="w-100 rounded d-flex justify-content-center deskripsi2 text-light h-50">
                <div class="w-75 mt-5 mb-5">
                    <form action="/komentar" method="post">
                        @csrf
                        <h2>Your Opinions</h2>
                        <input type="hidden" name="game_id" value="{{ $dataku->game_id }}">
                        <input type="hidden" name="user_id" value="{{ $user_id->user_id }}">
                        <input type="hidden" name="kategori_id" value="{{ $dataku->kategori_id }} col-md-6">
                        <textarea class="form-control mt-3 pb-5  text-light" name="komentar" style="background-color: rgb(32, 32, 32)" placeholder="isi pendapatmu......"></textarea>
                        <input class="btn btn-primary mt-3" type="submit" value="Submit" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    </form>
                </div>
                
            </div>
        </div>

  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Terkirim cuyyyy
          homesate
        </div>
        <div class="modal-footer p-3 mt-1">
        </div>
      </div>
    </div>
  </div>


{{-- guna tapi ndak penting --}}






@endsection

resources/views/sesi/user/hasilsrc.blade.php
@extends('basic.main')
@include('komponen.navback')
@section('konten')

<div class="w-100 d-flex justify-content-center">
    <div class="w-75 d-flex justify-content-start">
    @foreach($games as $item)
    @php $path = Storage::url('imgs/'.$item->poster_file); @endphp

    <div class="game rounded col-md-3 bg-dark m-2 mb-5 mt-5" style="width: 16rem;">
        <img src="{{ url($path) }}"alt="" srcset="" class="rounded-top" width="100%">
        <div class="ms-2">
            <h5 class="fw-bold text-light  mt-1" style="height: 10%">{{ $item->name_game }}</h5>
            <div class="d-flex" style="height: 10%">
            <div>
                <p class="fw-bold text-decoration-line-through fst-italic fw-light text-secondary">$00.000</p>
                <p class="fw-bold text-light m-0">$00.000</p>
            </div>
            <form class="w-100 justify-content-end text-center mt-4" action="/detail" method="POST">
                @csrf
                <input type="hidden" name="game_id" value="{{ $item->game_id }} col-md-6">
                <input type="hidden" name="kategori_id" value="{{ $item->kategori_id }} col-md-6">
                <button type="submit" name="submit" class="w-75 btn btn-outline-light">Detail</button>
            </form>
            </div>

        </div>
    </div>
    @endforeach
    </div>
</div>

@endsection

resources/views/sesi/user/komentar.blade.php
@extends('basic.main')
@include('komponen.navback')

@section('konten')

@foreach ($komen as $item)
    @foreach($user as $foto)
    @php $path = Storage::url('imgs/'.$foto->profil_img); @endphp
    <div class="w-100 d-flex justify-content-center text-center ">
        <div class="w-75 text-light border border-light rounded text-center mb-3" style="height: 250px">
            <div class="w-100 text-end">
                <form action="komentar/delete" method="post">
                    @csrf
                    <input type="hidden" name="id" id="id" value="{{ $item->id }}">
                    <button class="fw-bold btn btn-dark me-3">X</button>
                </form>
            </div>
            <div class="w-100 d-flex m-3">
                <div class="w-50 d-flex">
                    <img src="{{ url($path) }}" alt="" width="50px" height="50px" class="rounded-circle" srcset="">
                    <h3 class="mt-2 ms-2">{{ $foto->username }}</h3>
                </div>
                
                <div class="w-50 text-end">
                    <p class="fw-bold me-5">{{$item->updated_at}}</p>
                </div>
            </div>
            <p class="mt-5">"{{ $item->komentar }}"</p>
        </div>
    </div>
    @endforeach
@endforeach

resources/views/sesi/user/morekategori.blade.php
@extends('basic.main')
@section('konten')
@include('komponen.navback')
    <div class="w-100 d-flex justify-content-center">
        <div class="layer d-flex justify-content-center">
            <h1>Top</h1>
            <div class="d-flex row">
                @foreach($data as $item)
                @php $path = Storage::url('imgs/'.$item->poster_file); @endphp

                    <div class="game rounded col-md-3 bg-dark m-2 mb-5 mt-5" style="width: 16rem;">
                        <img src="{{ url($path) }}"alt="" srcset="" class="rounded-top" width="100%" height="350px">
                        <div class="ms-2">
                            <h5 class="fw-bold text-light  mt-1" style="height: 10%">{{ $item->name_game }}</h5>
                            <div class="d-flex" style="height: 10%">
                            <div>
                                <p class="fw-bold text-decoration-line-through fst-italic fw-light text-secondary">$00.000</p>
                                <p class="fw-bold text-light m-0">$00.000</p>
                            </div>
                            <form class="w-100 justify-content-end text-center mt-4" action="/detail" method="POST">
                                @csrf
                                <input type="hidden" name="game_id" value="{{ $item->game_id }} col-md-6">
                                <input type="hidden" name="kategori_id" value="{{ $item->kategori_id }} col-md-6">
                                <button type="submit" name="submit" class="w-75 btn btn-outline-light">Detail</button>
                            </form>
                            </div>
    
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/sesi/user/profil.blade.php
@extends('basic.main')
@include('komponen.navback')

@section('konten')
@php
use Illuminate\Support\Facades\DB;   
@endphp
@php $path = Storage::url('imgs/'.$data->profil_img); @endphp
<div class="w-100 d-flex justify-content-center mt-5">
    <div class="layer row">
        <div class="col-lg-8 d-flex mt-4">
            <img src="{{ url($path) }}" width="200px" height="200px" alt="" srcset="" class="  border border-light">
            <div class="text-start">
                <h1 class="text-light ms-3 w-100">{{ $data->username }}</h1>
                <h4 class="text-light ms-3 w-100">{{ $data->email }}</h4>
            </div>
        </div>
        <div class="col-lg-4 mt-4">
            <a class="btn btn-outline-light p-2 w-100" href="{{ route('profil.edit',$data->id) }}">Edit</a>
        </div>
    </div>
</div>

<div class="w-100 d-flex justify-content-center mt-5">
    <div class="layer row">
        <div class="col-lg-8 ">
            <h4 class="fw-bold text-light">Favorit Game</h4>
            <div class="d-flex mt-3">
                @foreach($game_coba as $item)
                @php $game = DB::table('games')->where('game_id', $item->game_id)->first(); @endphp
                @php $path = Storage::url('imgs/'.$game->poster_file); @endphp
            
                <div class="game rounded  bg-dark me-2 " style="width: 12.5rem;">
                    <img class="w-100" src="{{ url($path) }}"alt="" srcset="" class="rounded-top" >
                    <div class="ms-2">
                        <h5 class="fw-bold text-light  mt-1" style="height: 10%">{{ $game->name_game }}</h5>
                        <div class="d-flex" style="height: 10%">
                        <div>
                            <p class="fw-bold text-decoration-line-through fst-italic fw-light text-secondary">$00.000</p>
                            <p class="fw-bold text-light m-0">$00.000</p>
                        </div>
                        <form class="w-100 justify-content-end text-center mt-4" action="/detail" method="POST">
                            @csrf
                            <input type="hidden" name="game_id" value="{{ $game->game_id }}">
                            <input type="hidden" name="kategori_id" value="{{ $game->kategori_id }}">
                            <button type="submit" name="submit" class="w-75 btn btn-outline-light">Detail</button>
                        </form>
                        </div>
            
                    </div>
                </div>
                @endforeach
            </div>

        </div>

        <div class=" col-lg-4">
            <div class="d-flex">
                <h4 class="w-50 fw-bold text-light">Your Comment</h4>
                <a class="w-50 text-end text-decoration-none" href="/komentar">Other</a>
            </div>
            @php $komen = DB::table('komentars')->where('user_id', $data->user_id)->paginate(3); @endphp
            @foreach ($komen as $kom)
                <div class="mt-3 text-light">
                    <p class="fw-bold m-0">{{ $kom->created_at }}</p>
                    
                    <p>"{{ $kom->komentar }}"</p>
                </div>
            @endforeach
        </div>
    </div>
</div>

<div class="w-100 d-flex justify-content-center mt-5 text-light ">
    <div class="layer ">
        <h4>Other Information</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit assumenda labore quis maiores error culpa eveniet saepe quaerat molestias aspernatur soluta maxime vero ex, in commodi minus minima ducimus sequi.</p>
    </div>

</div>


@endsection

resources/views/sesi/user/profiledit.blade.php
@extends('basic.main')
@section('konten')
@include('komponen.navback')
<h1>saya suka keqingggg</h1>
@php $path = Storage::url('imgs/'.$data->profil_img); @endphp

<div  class="w-100 d-flex justify-content-center">
    <div class="layer text-light">
        <div class="w-100 row">
        
                    <div class="d-flex mb-4 mt-4">
                        <div class="">
                            <img src="{{ url($path) }}" width="200px" height="" alt="" srcset="" class="  border border-light ">
                        </div>
                        <div class="ms-4">
                            <h2 class="mt-2">{{ $data->username }}</h2>
                            <p class="mt-1 fw-bold">{{ $data->email }}</p>
                        </div>
                    </div>
                    <form class=" text-light" action="{{ route('profil.update',$data->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <h1 class="text-light">Edit Profil</h1>
                        <div class="mb-2 d-flex w-100 mt-4">
                            <label for="profil_img" class="formlabel w-25">foto profil</label>
                            <input type="file" class="form-control bg-dark text-light" name="profil_img" value="{{ $data->profil_img }}" placeholder="{{ $data->profil_img }}">
                        </div>
                        <div class="mb-2 d-flex w-100">
                            <label for="usernamename" class="formlabel w-25">username</label>
                            <input type="text" class="form-control bg-dark text-light" name="username" value="{{ $data->username }}" placeholder="">
                            <input type="hidden" name="user_id" value="{{ $data->user_id }}">
                        </div>
                        <div class="mb-2 d-flex w-100">
                            <label for="email" class="formlabel w-25">email</label>
                            <input type="text" class="form-control bg-dark text-light" name="email" value="{{ $data->email }}" placeholder="">
                        </div>
                        <div class="mb-2 mt-3 d-grid">
                            <button class="btn btn-secondary" type="submit" name="submit">submit</button>
                        </div>
                    </form>
            
        
            
        </div>
    </div>
</div>

@endsection